from .index import *
from .login import *
from .register import *
from .add_child import *
from .create_event import *
from .manage_event import *
from .add_game import *
from .add_genre import *
from .remove_child import *
from .browse import *
from .leaderboard import *