# Generated by Django 4.2.6 on 2023-10-08 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="volunteer", name="id",),
        migrations.AlterField(
            model_name="volunteer",
            name="player",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="tournaments.player",
            ),
        ),
    ]
