# Generated by Django 4.2.6 on 2023-10-08 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0002_remove_volunteer_id_alter_volunteer_player"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="max_no_of_players",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="event", name="online", field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="event",
            name="players",
            field=models.ManyToManyField(to="tournaments.player"),
        ),
        migrations.AddField(
            model_name="event",
            name="staff",
            field=models.ManyToManyField(to="tournaments.staff"),
        ),
    ]
