# Generated by Django 4.2.6 on 2023-10-08 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_kid_favourite_genres_alter_kid_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kid',
            name='favourite_genres',
        ),
        migrations.AddField(
            model_name='kid',
            name='favourite_genre',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
